import { useState } from "react";

// ═══════════════════════════════════════════════════════════════
//  CONFIG GENERATORS
// ═══════════════════════════════════════════════════════════════

const genManagerYaml = (c) => `_meta:
  version: 3

# ┌─────────────────────────────────────────────────────────┐
# │  Flamenco Manager Config — generated by Setup Wizard    │
# │  Deploy to: ${(c.managerHostname + " ".repeat(20)).slice(0,20)} (${c.managerIP})${"".padEnd(14)}│
# └─────────────────────────────────────────────────────────┘

# SQLite database for job tracking
database: flamenco-manager.sqlite

# Manager's own local storage
local_manager_storage_path: ./flamenco-manager-storage/

# !! SHARED PATH — must be accessible from ALL machines on the network
# Workers reach this via UNC: ${c.sharedPathUNC}
shared_storage_path: "${c.sharedPathUNC.replace(/\\\\/g, "/")}"

# Manager listens on this port (workers connect here)
listen: :${c.managerPort}

task_timeout: 10m0s
worker_cleanup_max_age: 1h0m0s

shaman:
  enabled: true
  garbageCollect:
    enabled: true
    maxAge: 744h0m0s
    extraCheckoutPaths: []
`;

const genWorkerYaml = (c) => `# ┌─────────────────────────────────────────────────────────┐
# │  Flamenco Worker Config — generated by Setup Wizard     │
# │  Deploy to: ${(c.workerHostname + " ".repeat(20)).slice(0,20)} (${c.workerIP})${"".padEnd(14)}│
# └─────────────────────────────────────────────────────────┘

# URL of the Flamenco Manager
manager_url: http://${c.managerIP}:${c.managerPort}/

# Worker display name in the dashboard
worker_name: "${c.workerHostname}"
`;

const genManagerBat = (c) => `@echo off
:: ═══════════════════════════════════════════════════════════════
:: Flamenco MANAGER — Setup & Launch
:: Machine : ${c.managerHostname} (${c.managerIP})
:: Generated by Flamenco Setup Wizard
:: ═══════════════════════════════════════════════════════════════
setlocal enabledelayedexpansion
color 0E
title Flamenco Manager — ${c.managerHostname}

echo.
echo  [FLAMENCO MANAGER SETUP]
echo  Machine : ${c.managerHostname} (${c.managerIP})
echo  Port    : ${c.managerPort}
echo  Storage : ${c.sharedLocalPath}
echo.

:: ── AND gate: exe must exist ───────────────────────────────────
if not exist "%~dp0flamenco-manager.exe" (
    echo  [FAIL] flamenco-manager.exe not found
    echo         Download: https://flamenco.blender.org/download/
    echo         Place it in the same folder as this .bat file
    pause & exit /b 1
)
echo  [OK]   flamenco-manager.exe found

:: ── AND gate: config must exist ────────────────────────────────
if not exist "%~dp0flamenco-manager.yaml" (
    echo  [FAIL] flamenco-manager.yaml not found
    echo         Copy the generated yaml file to %~dp0
    pause & exit /b 1
)
echo  [OK]   flamenco-manager.yaml found

:: ── Check/create shared storage folder ─────────────────────────
if not exist "${c.sharedLocalPath}" (
    echo  [+]    Creating shared folder...
    mkdir "${c.sharedLocalPath}"
    echo  [OK]   Created: ${c.sharedLocalPath}
) else (
    echo  [OK]   Shared folder exists
)

:: ── Check Blender ───────────────────────────────────────────────
if not exist "${c.blenderPathManager}" (
    echo  [WARN] Blender not found at:
    echo         ${c.blenderPathManager}
    echo         Update shared_storage_path in flamenco-manager.yaml if needed
) else (
    echo  [OK]   Blender found
)

${c.firewallAlreadyOpen
  ? `:: ── SKIP firewall (already open) ──────────────────────────────
echo  [SKIP] Firewall port ${c.managerPort} already open`
  : `:: ── Open firewall port ${c.managerPort} ─────────────────────────────────
echo  [+]    Configuring Windows Firewall...
netsh advfirewall firewall show rule name="Flamenco Manager ${c.managerPort}" >nul 2>&1
if errorlevel 1 (
    netsh advfirewall firewall add rule name="Flamenco Manager ${c.managerPort}" dir=in action=allow protocol=TCP localport=${c.managerPort} >nul
    echo  [OK]   Firewall port ${c.managerPort} opened
) else (
    echo  [OK]   Firewall rule already exists
)`}

echo.
echo  ─────────────────────────────────────────────────────────
echo  Dashboard: http://${c.managerIP}:${c.managerPort}/
echo  Workers connect to: http://${c.managerIP}:${c.managerPort}/
echo  ─────────────────────────────────────────────────────────
echo.
echo  Starting Flamenco Manager... (Ctrl+C to stop)
echo.
"%~dp0flamenco-manager.exe"
pause
`;

const genWorkerBat = (c) => `@echo off
:: ═══════════════════════════════════════════════════════════════
:: Flamenco WORKER — Setup & Launch
:: Machine : ${c.workerHostname} (${c.workerIP})
:: Generated by Flamenco Setup Wizard
:: ═══════════════════════════════════════════════════════════════
setlocal enabledelayedexpansion
color 0A
title Flamenco Worker — ${c.workerHostname}

echo.
echo  [FLAMENCO WORKER SETUP]
echo  Machine : ${c.workerHostname} (${c.workerIP})
echo  Manager : http://${c.managerIP}:${c.managerPort}/
echo.

:: ── AND gate: exe must exist ───────────────────────────────────
if not exist "%~dp0flamenco-worker.exe" (
    echo  [FAIL] flamenco-worker.exe not found
    echo         Download: https://flamenco.blender.org/download/
    echo         Place it in the same folder as this .bat file
    pause & exit /b 1
)
echo  [OK]   flamenco-worker.exe found

:: ── AND gate: config must exist ────────────────────────────────
if not exist "%~dp0flamenco-worker.yaml" (
    echo  [FAIL] flamenco-worker.yaml not found
    echo         Copy the generated yaml file to %~dp0
    pause & exit /b 1
)
echo  [OK]   flamenco-worker.yaml found

:: ── AND gate: Blender must be installed ────────────────────────
if not exist "${c.blenderPathWorker}" (
    echo  [FAIL] Blender not found at:
    echo         ${c.blenderPathWorker}
    echo         Install Blender or update flamenco-worker.yaml with the correct path
    pause & exit /b 1
)
echo  [OK]   Blender found

:: ── AND gate: shared storage must be reachable ─────────────────
if not exist "${c.sharedPathUNC}" (
    echo  [FAIL] Cannot reach shared storage: ${c.sharedPathUNC}
    echo         Make sure:
    echo           1. ${c.managerHostname} is online and sharing the folder
    echo           2. You ran setup_share.bat on ${c.managerHostname}
    echo           3. Windows can resolve hostname: ${c.managerHostname}
    echo              (try pinging it, or use the IP instead: \\\\${c.managerIP}\\FlamencoShared)
    pause & exit /b 1
)
echo  [OK]   Shared storage accessible

:: ── OR gate: manager reachable? ────────────────────────────────
ping -n 1 ${c.managerIP} >nul 2>&1
if errorlevel 1 (
    echo  [WARN] Cannot ping manager at ${c.managerIP}
    echo         Worker will still attempt to connect — continuing...
) else (
    echo  [OK]   Manager reachable (${c.managerIP})
)

echo.
echo  ─────────────────────────────────────────────────────────
echo  Connecting to manager: http://${c.managerIP}:${c.managerPort}/
echo  ─────────────────────────────────────────────────────────
echo.
echo  Starting Flamenco Worker... (Ctrl+C to stop)
echo.
"%~dp0flamenco-worker.exe"
pause
`;

const genShareBat = (c) => `@echo off
:: ═══════════════════════════════════════════════════════════════
:: Create Windows Network Share for Flamenco
:: Run on ${c.managerHostname} as Administrator
:: Generated by Flamenco Setup Wizard
:: ═══════════════════════════════════════════════════════════════
setlocal
color 0D
title Flamenco — Create Network Share

echo.
echo  [FLAMENCO SHARED STORAGE SETUP]
echo  Creating share on: ${c.managerHostname}
echo  Local path  : ${c.sharedLocalPath}
echo  Network path: ${c.sharedPathUNC}
echo.

:: Check we're running as admin
net session >nul 2>&1
if errorlevel 1 (
    echo  [FAIL] This script must be run as Administrator
    echo         Right-click the .bat file and choose "Run as administrator"
    pause & exit /b 1
)
echo  [OK]   Running as Administrator

:: Create local folder
if not exist "${c.sharedLocalPath}" (
    mkdir "${c.sharedLocalPath}"
    echo  [OK]   Created folder: ${c.sharedLocalPath}
) else (
    echo  [OK]   Folder already exists
)

:: Remove existing share if present (clean slate)
net share FlamencoShared >nul 2>&1
if not errorlevel 1 (
    echo  [+]    Removing existing share...
    net share FlamencoShared /delete >nul
)

:: Create the share with full access for Everyone (local network)
net share FlamencoShared="${c.sharedLocalPath}" /GRANT:Everyone,FULL /REMARK:"Flamenco Render Farm Shared Storage"
if errorlevel 1 (
    echo  [FAIL] Failed to create share — check folder permissions
    pause & exit /b 1
)

echo.
echo  [OK]   Share created successfully
echo  ─────────────────────────────────────────────────────────
echo  Workers access this at: ${c.sharedPathUNC}
echo  ─────────────────────────────────────────────────────────
echo.
pause
`;

const genFirewallBat = (c) => `@echo off
:: ═══════════════════════════════════════════════════════════════
:: Flamenco Firewall Rules
:: Run on ${c.managerHostname} as Administrator
:: Generated by Flamenco Setup Wizard
:: ═══════════════════════════════════════════════════════════════
setlocal
color 0C
title Flamenco — Firewall Setup

echo.
echo  [FLAMENCO FIREWALL SETUP]
echo  Opening port ${c.managerPort} on ${c.managerHostname}
echo.

net session >nul 2>&1
if errorlevel 1 (
    echo  [FAIL] Must run as Administrator
    pause & exit /b 1
)

:: Remove old rules first
netsh advfirewall firewall delete rule name="Flamenco Manager ${c.managerPort}" >nul 2>&1

:: Inbound: workers connect to manager
netsh advfirewall firewall add rule ^
  name="Flamenco Manager ${c.managerPort}" ^
  dir=in action=allow protocol=TCP localport=${c.managerPort} ^
  description="Flamenco render farm manager inbound"

:: Outbound
netsh advfirewall firewall add rule ^
  name="Flamenco Manager ${c.managerPort} Out" ^
  dir=out action=allow protocol=TCP localport=${c.managerPort}

echo.
echo  [OK]   Firewall rules added for TCP port ${c.managerPort}
echo         Workers on the local network can now reach the manager.
echo.
pause
`;

// ═══════════════════════════════════════════════════════════════
//  DESIGN TOKENS
// ═══════════════════════════════════════════════════════════════

const T = {
  bg: "#050505",
  card: "#0a0a0a",
  surface: "#0f0f0f",
  border: "#1a1a1a",
  border2: "#2a2a2a",
  amber: "#f59e0b",
  blue: "#60a5fa",
  purple: "#a78bfa",
  green: "#4ade80",
  red: "#f87171",
  text: "#e5e7eb",
  muted: "#6b7280",
  dim: "#374151",
  mono: "'JetBrains Mono', 'Cascadia Code', 'Consolas', monospace",
};

// ═══════════════════════════════════════════════════════════════
//  PRIMITIVES
// ═══════════════════════════════════════════════════════════════

function Field({ label, value, onChange, placeholder, hint, wide }) {
  const [focused, setFocused] = useState(false);
  return (
    <div style={{ marginBottom: "1.1rem", gridColumn: wide ? "1 / -1" : undefined }}>
      <label style={{
        display: "block", color: T.amber, fontSize: "0.66rem",
        letterSpacing: "0.16em", textTransform: "uppercase",
        marginBottom: "0.35rem", fontFamily: T.mono,
      }}>
        {label}
      </label>
      <input
        value={value}
        onChange={e => onChange(e.target.value)}
        placeholder={placeholder}
        onFocus={() => setFocused(true)}
        onBlur={() => setFocused(false)}
        style={{
          width: "100%", boxSizing: "border-box",
          background: T.surface, border: `1px solid ${focused ? T.amber + "88" : T.border2}`,
          color: T.text, padding: "0.55rem 0.8rem",
          fontFamily: T.mono, fontSize: "0.8rem",
          borderRadius: "3px", outline: "none",
          transition: "border-color 0.15s",
        }}
      />
      {hint && (
        <div style={{ color: T.dim, fontSize: "0.66rem", marginTop: "0.3rem", fontFamily: T.mono }}>
          ↳ {hint}
        </div>
      )}
    </div>
  );
}

function Toggle({ label, checked, onChange, hint }) {
  return (
    <div
      onClick={() => onChange(!checked)}
      style={{ display: "flex", gap: "0.75rem", marginBottom: "1.1rem", cursor: "pointer", alignItems: "flex-start" }}
    >
      <div style={{
        width: 38, height: 20, borderRadius: 10, flexShrink: 0,
        background: checked ? T.amber : T.border2,
        position: "relative", transition: "background 0.18s", marginTop: 2,
      }}>
        <div style={{
          width: 16, height: 16, borderRadius: "50%", background: "#fff",
          position: "absolute", top: 2, left: checked ? 20 : 2,
          transition: "left 0.18s", boxShadow: "0 1px 3px rgba(0,0,0,0.5)",
        }} />
      </div>
      <div>
        <div style={{ color: T.text, fontSize: "0.8rem", fontFamily: T.mono }}>{label}</div>
        {hint && <div style={{ color: T.dim, fontSize: "0.66rem", marginTop: "0.2rem", fontFamily: T.mono }}>↳ {hint}</div>}
      </div>
    </div>
  );
}

function Btn({ children, onClick, secondary, disabled, small }) {
  const [hov, setHov] = useState(false);
  return (
    <button
      onClick={!disabled ? onClick : undefined}
      onMouseEnter={() => setHov(true)}
      onMouseLeave={() => setHov(false)}
      style={{
        background: secondary
          ? hov ? T.border2 : "transparent"
          : disabled ? "#111"
          : hov ? "#fbbf24" : T.amber,
        color: secondary ? T.muted : disabled ? "#2a2a2a" : "#000",
        border: secondary ? `1px solid ${T.border2}` : "none",
        padding: small ? "0.35rem 0.8rem" : "0.6rem 1.4rem",
        fontFamily: T.mono, fontSize: small ? "0.7rem" : "0.76rem",
        fontWeight: "700", letterSpacing: "0.1em", textTransform: "uppercase",
        cursor: disabled ? "not-allowed" : "pointer",
        borderRadius: "3px", transition: "all 0.12s",
      }}
    >
      {children}
    </button>
  );
}

function Tag({ children, color = T.amber }) {
  return (
    <span style={{
      background: color + "18", border: `1px solid ${color}44`,
      color, padding: "0.12rem 0.45rem",
      fontSize: "0.64rem", fontFamily: T.mono,
      borderRadius: "2px", letterSpacing: "0.1em", textTransform: "uppercase",
    }}>
      {children}
    </span>
  );
}

function InfoBox({ title, children, color = T.amber }) {
  return (
    <div style={{
      background: T.surface, border: `1px solid ${color}22`,
      borderLeft: `3px solid ${color}`, borderRadius: "3px",
      padding: "0.9rem 1rem", marginBottom: "1.2rem",
    }}>
      {title && (
        <div style={{ color, fontSize: "0.64rem", letterSpacing: "0.14em", textTransform: "uppercase", fontFamily: T.mono, marginBottom: "0.5rem" }}>
          {title}
        </div>
      )}
      <div style={{ color: T.muted, fontSize: "0.74rem", fontFamily: T.mono, lineHeight: 1.7 }}>
        {children}
      </div>
    </div>
  );
}

function NavRow({ onBack, onNext, nextDisabled, nextLabel = "Next →", showBack = true }) {
  return (
    <div style={{ display: "flex", gap: "0.6rem", marginTop: "1.8rem" }}>
      {showBack && <Btn secondary onClick={onBack}>← Back</Btn>}
      <Btn onClick={onNext} disabled={nextDisabled}>{nextLabel}</Btn>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════
//  STEPS
// ═══════════════════════════════════════════════════════════════

function StepIntro({ onNext }) {
  return (
    <div>
      <div style={{ marginBottom: "1.8rem" }}>
        <div style={{ color: T.amber, fontSize: "0.66rem", letterSpacing: "0.2em", textTransform: "uppercase", fontFamily: T.mono, marginBottom: "0.6rem" }}>
          Flamenco 3.x · Windows 11 Pro · 2-Machine Setup
        </div>
        <h1 style={{ color: T.text, fontSize: "2rem", fontWeight: "900", margin: 0, fontFamily: T.mono, lineHeight: 1.15 }}>
          Render Farm<br />
          <span style={{ color: T.amber }}>Setup Wizard</span>
        </h1>
      </div>

      <p style={{ color: T.muted, fontFamily: T.mono, fontSize: "0.8rem", lineHeight: 1.8, marginBottom: "1.5rem" }}>
        Walk through configuring both machines step-by-step.<br />
        This wizard generates all config files and batch scripts.
      </p>

      <InfoBox title="What you'll need" color={T.amber}>
        {[
          "Both PCs on the same local network (same subnet)",
          "Blender installed on both machines",
          "flamenco-manager.exe + flamenco-worker.exe downloaded",
          "Admin access on the manager machine (for sharing + firewall)",
        ].map((item, i) => (
          <div key={i} style={{ display: "flex", gap: "0.6rem", marginBottom: "0.35rem" }}>
            <span style={{ color: T.amber, flexShrink: 0 }}>▸</span>
            <span style={{ color: T.text }}>{item}</span>
          </div>
        ))}
        <div style={{ marginTop: "0.75rem", paddingTop: "0.75rem", borderTop: `1px solid ${T.border}` }}>
          <a href="https://flamenco.blender.org/download/" target="_blank" rel="noreferrer"
            style={{ color: T.blue, fontSize: "0.72rem", textDecoration: "none" }}>
            → flamenco.blender.org/download/
          </a>
        </div>
      </InfoBox>

      <Btn onClick={onNext}>Begin Setup →</Btn>
    </div>
  );
}

function StepWindowsCheck({ config, update, onNext, onBack }) {
  const choice = config.windowsPro;
  return (
    <div>
      <h2 style={{ color: T.text, fontFamily: T.mono, fontSize: "1.15rem", fontWeight: "800", margin: "0 0 0.3rem" }}>
        Windows Version Check
      </h2>
      <p style={{ color: T.muted, fontFamily: T.mono, fontSize: "0.78rem", marginBottom: "1.5rem", lineHeight: 1.7 }}>
        Flamenco's network share setup requires features only available in
        <span style={{ color: T.amber }}> Windows 11 Pro</span> or higher.
        This must be true for <strong style={{ color: T.text }}>both machines</strong>.
      </p>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.75rem", marginBottom: "1.5rem" }}>
        {[
          {
            val: true, icon: "✅",
            title: "Both machines are Windows 11 Pro",
            desc: "Pro, Education, or Enterprise — all work fine",
            color: T.green,
          },
          {
            val: false, icon: "🚫",
            title: "One or both machines are Windows 11 Home",
            desc: "Home edition — network sharing features are restricted",
            color: T.red,
          },
        ].map(({ val, icon, title, desc, color }) => (
          <div
            key={String(val)}
            onClick={() => update("windowsPro", val)}
            style={{
              background: choice === val ? color + "18" : T.surface,
              border: `2px solid ${choice === val ? color : T.border2}`,
              borderRadius: "4px", padding: "1rem",
              cursor: "pointer", transition: "all 0.15s",
            }}
          >
            <div style={{ fontSize: "1.3rem", marginBottom: "0.4rem" }}>{icon}</div>
            <div style={{ color: choice === val ? color : T.text, fontFamily: T.mono, fontWeight: "700", fontSize: "0.8rem", marginBottom: "0.25rem" }}>{title}</div>
            <div style={{ color: T.dim, fontFamily: T.mono, fontSize: "0.68rem", lineHeight: 1.5 }}>{desc}</div>
          </div>
        ))}
      </div>

      {/* HOW TO CHECK */}
      <InfoBox title="How to check your Windows edition" color={T.amber}>
        Press <span style={{ color: T.text }}>Win + R</span> → type{" "}
        <code style={{ color: T.amber, background: "#1a1a1a", padding: "0.1rem 0.3rem", borderRadius: "2px" }}>winver</code>{" "}
        → press Enter. Look for <span style={{ color: T.text }}>"Windows 11 Pro"</span> in the title line.
        <br />Or: Settings → System → About → scroll to <span style={{ color: T.text }}>Windows specifications</span>.
      </InfoBox>

      {/* HARD STOP — HOME */}
      {choice === false && (
        <div style={{
          background: T.red + "12", border: `2px solid ${T.red}44`,
          borderLeft: `4px solid ${T.red}`,
          borderRadius: "4px", padding: "1.1rem", marginBottom: "1rem",
        }}>
          <div style={{ color: T.red, fontFamily: T.mono, fontSize: "0.68rem", letterSpacing: "0.14em", textTransform: "uppercase", marginBottom: "0.6rem" }}>
            ⛔ Cannot continue — Windows 11 Home is not compatible
          </div>
          <div style={{ color: T.muted, fontFamily: T.mono, fontSize: "0.74rem", lineHeight: 1.75 }}>
            There are two reasons Home won't work — and both matter.
            <br /><br />
            <span style={{ color: T.amber, fontWeight: "700" }}>1. SMB Network Sharing</span><br />
            The <code style={{ color: T.text }}>net share</code> command and credential-based
            authentication used by this setup require Pro or higher. Home restricts the server side of Windows file sharing.
            <br /><br />
            <span style={{ color: T.amber, fontWeight: "700" }}>2. Group Policy (GPO) — the one most guides miss</span><br />
            Windows Pro includes Group Policy Objects. These control firewall rules at a deeper level
            than the standard Windows Firewall. The default Flamenco port (8080) is blocked by GPO
            on many Pro machines — which is why this setup uses <strong style={{ color: T.text }}>port 80</strong> instead.
            Port 80 is whitelisted by Group Policy by default. Home has no GPO tools at all,
            making these conflicts impossible to manage properly.
            <br /><br />
            <span style={{ color: T.text, fontWeight: "700" }}>Your options:</span>
            <br />
            <span style={{ color: T.amber }}>▸</span>{" "}
            <strong style={{ color: T.text }}>Check for a dormant Pro licence first</strong> — many OEM machines ship with
            one never activated. Run <code style={{ color: T.amber, background: "#1a1a1a", padding: "0.1rem 0.3rem", borderRadius: "2px" }}>slmgr /dlv</code> in
            an admin Command Prompt to check.
            <br />
            <span style={{ color: T.amber }}>▸</span>{" "}
            <strong style={{ color: T.text }}>Upgrade in-place</strong> — Settings → System → Activation → Upgrade your edition.
            No reinstall. Keeps all files and apps.
            <br />
            <span style={{ color: T.amber }}>▸</span>{" "}
            <strong style={{ color: T.text }}>Get a key at a fair price</strong> — digital Pro keys are available
            for a fraction of RRP from reputable resellers. Link in the GitHub repo.
          </div>
        </div>
      )}

      {choice === true && (
        <InfoBox title="All clear" color={T.green}>
          Both machines are running a compatible edition. You are good to continue.
        </InfoBox>
      )}

      <NavRow onBack={onBack} onNext={onNext} nextDisabled={choice !== true} showBack={false} />
    </div>
  );
}

function StepRoles({ config, update, onNext, onBack }) {
  return (
    <div>
      <h2 style={{ color: T.text, fontFamily: T.mono, fontSize: "1.15rem", fontWeight: "800", margin: "0 0 0.3rem" }}>
        Machine Roles
      </h2>
      <p style={{ color: T.muted, fontFamily: T.mono, fontSize: "0.78rem", marginBottom: "1.5rem", lineHeight: 1.7 }}>
        One machine runs <Tag>Manager</Tag> (scheduler + dashboard).<br />
        Both machines run <Tag color={T.blue}>Worker</Tag> (renders frames).
      </p>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.75rem", marginBottom: "1.5rem" }}>
        {[
          { role: "Manager", color: T.amber, lines: ["flamenco-manager.exe", "Hosts web dashboard", "Manages job queue", "Hosts shared storage"] },
          { role: "Worker", color: T.blue, lines: ["flamenco-worker.exe", "Renders frames", "Connects to manager", "(also runs on manager PC)"] },
        ].map(({ role, color, lines }) => (
          <div key={role} style={{
            background: T.surface, border: `1px solid ${color}33`,
            borderRadius: "4px", padding: "1rem",
          }}>
            <div style={{ color, fontSize: "0.64rem", letterSpacing: "0.15em", textTransform: "uppercase", fontFamily: T.mono, marginBottom: "0.6rem" }}>
              {role}
            </div>
            {lines.map((l, i) => (
              <div key={i} style={{ color: i === 0 ? T.text : T.dim, fontSize: "0.72rem", fontFamily: T.mono, marginBottom: "0.2rem" }}>
                {l}
              </div>
            ))}
          </div>
        ))}
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
        <Field
          label="Manager PC hostname"
          value={config.managerHostname}
          onChange={v => {
            update("managerHostname", v);
            const folder = config.sharedLocalPath.split("\\").pop() || "FlamencoShared";
            update("sharedPathUNC", `\\\\${v}\\${folder}`);
          }}
          placeholder="RENDER-MANAGER"
          hint="Run 'hostname' in cmd"
        />
        <Field
          label="Worker PC hostname"
          value={config.workerHostname}
          onChange={v => update("workerHostname", v)}
          placeholder="RENDER-WORKER"
          hint="Run 'hostname' in cmd"
        />
      </div>

      <NavRow onBack={onBack} onNext={onNext} nextDisabled={!config.managerHostname || !config.workerHostname} showBack={false} />
    </div>
  );
}

function StepNetwork({ config, update, onNext, onBack }) {
  return (
    <div>
      <h2 style={{ color: T.text, fontFamily: T.mono, fontSize: "1.15rem", fontWeight: "800", margin: "0 0 0.3rem" }}>
        Network
      </h2>
      <p style={{ color: T.muted, fontFamily: T.mono, fontSize: "0.78rem", marginBottom: "1.5rem", lineHeight: 1.7 }}>
        Enter IP addresses for both machines.<br />
        Run <code style={{ background: T.surface, padding: "0.1rem 0.35rem", borderRadius: "2px", color: T.text }}>ipconfig</code> in cmd to find them.
        Use static IPs or DHCP reservations so they don't change.
      </p>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
        <Field
          label={`Manager IP — ${config.managerHostname}`}
          value={config.managerIP}
          onChange={v => update("managerIP", v)}
          placeholder="192.168.1.100"
          hint="Hosts the manager service"
        />
        <Field
          label={`Worker IP — ${config.workerHostname}`}
          value={config.workerIP}
          onChange={v => update("workerIP", v)}
          placeholder="192.168.1.101"
          hint="Runs the render worker"
        />
      </div>
      <Field
        label="Manager Port"
        value={config.managerPort}
        onChange={v => update("managerPort", v)}
        placeholder="8080"
        hint="Default 8080 — change if this port is already in use"
      />

      {config.managerIP && (
        <InfoBox title="Dashboard URL" color={T.blue}>
          <span style={{ color: T.blue }}>http://{config.managerIP}:{config.managerPort}/</span>
          <span style={{ color: T.dim }}> — open in any browser on your network</span>
        </InfoBox>
      )}

      <NavRow onBack={onBack} onNext={onNext} nextDisabled={!config.managerIP || !config.workerIP} />
    </div>
  );
}

function StepStorage({ config, update, onNext, onBack }) {
  const handleLocalPath = (v) => {
    update("sharedLocalPath", v);
    const parts = v.replace(/\\/g, "\\").split("\\").filter(Boolean);
    const folderName = parts[parts.length - 1] || "FlamencoShared";
    update("sharedPathUNC", `\\\\${config.managerHostname}\\${folderName}`);
  };

  return (
    <div>
      <h2 style={{ color: T.text, fontFamily: T.mono, fontSize: "1.15rem", fontWeight: "800", margin: "0 0 0.3rem" }}>
        Shared Storage
      </h2>
      <p style={{ color: T.muted, fontFamily: T.mono, fontSize: "0.78rem", marginBottom: "1.5rem", lineHeight: 1.7 }}>
        Both machines read/write the same folder.<br />
        It lives on <Tag>{config.managerHostname}</Tag> and is shared over the network via Windows Sharing.
      </p>

      <Toggle
        label="Network share already created"
        checked={config.shareAlreadyCreated}
        onChange={v => update("shareAlreadyCreated", v)}
        hint={config.shareAlreadyCreated ? "Skip — setup_share.bat won't be generated" : "Generate setup_share.bat to create it automatically"}
      />

      <Field
        label={`Local folder path on ${config.managerHostname}`}
        value={config.sharedLocalPath}
        onChange={handleLocalPath}
        placeholder="C:\FlamencoShared"
        hint="This folder will be created if it doesn't exist, then shared"
      />
      <Field
        label="UNC path (how workers and yaml will access it)"
        value={config.sharedPathUNC}
        onChange={v => update("sharedPathUNC", v)}
        placeholder={`\\\\${config.managerHostname}\\FlamencoShared`}
        hint="Must match the Windows share name exactly"
      />

      {!config.shareAlreadyCreated && (
        <InfoBox title="Will generate: setup_share.bat" color={T.purple}>
          Run as Administrator on <Tag color={T.purple}>{config.managerHostname}</Tag> — creates the folder and Windows share automatically.
        </InfoBox>
      )}

      <NavRow onBack={onBack} onNext={onNext} nextDisabled={!config.sharedLocalPath || !config.sharedPathUNC} />
    </div>
  );
}

function StepBlender({ config, update, onNext, onBack }) {
  const [sameOnBoth, setSameOnBoth] = useState(
    config.blenderPathManager === config.blenderPathWorker
  );

  const handleManagerPath = (v) => {
    update("blenderPathManager", v);
    if (sameOnBoth) update("blenderPathWorker", v);
  };

  return (
    <div>
      <h2 style={{ color: T.text, fontFamily: T.mono, fontSize: "1.15rem", fontWeight: "800", margin: "0 0 0.3rem" }}>
        Blender Paths
      </h2>
      <p style={{ color: T.muted, fontFamily: T.mono, fontSize: "0.78rem", marginBottom: "1.5rem", lineHeight: 1.7 }}>
        Full path to <code style={{ background: T.surface, padding: "0.1rem 0.3rem", borderRadius: "2px", color: T.text }}>blender.exe</code> on each machine.<br />
        Used by the worker bat script to verify Blender is installed.
      </p>

      <Toggle
        label="Same install path on both machines"
        checked={sameOnBoth}
        onChange={v => {
          setSameOnBoth(v);
          if (v) update("blenderPathWorker", config.blenderPathManager);
        }}
        hint="Most common case — same default install path on both PCs"
      />

      <Field
        label={sameOnBoth ? "Blender path (both machines)" : `Blender path — ${config.managerHostname}`}
        value={config.blenderPathManager}
        onChange={handleManagerPath}
        placeholder="C:\Program Files\Blender Foundation\Blender 4.2\blender.exe"
        hint="Full path including blender.exe"
      />

      {!sameOnBoth && (
        <Field
          label={`Blender path — ${config.workerHostname}`}
          value={config.blenderPathWorker}
          onChange={v => update("blenderPathWorker", v)}
          placeholder="C:\Program Files\Blender Foundation\Blender 4.2\blender.exe"
          hint="Full path on the worker machine"
        />
      )}

      <NavRow onBack={onBack} onNext={onNext} nextDisabled={!config.blenderPathManager} />
    </div>
  );
}

function StepFirewall({ config, update, onNext, onBack }) {
  return (
    <div>
      <h2 style={{ color: T.text, fontFamily: T.mono, fontSize: "1.15rem", fontWeight: "800", margin: "0 0 0.3rem" }}>
        Firewall
      </h2>
      <p style={{ color: T.muted, fontFamily: T.mono, fontSize: "0.78rem", marginBottom: "1.5rem", lineHeight: 1.7 }}>
        Workers on <Tag color={T.blue}>{config.workerHostname}</Tag> connect to the manager on TCP port {config.managerPort}.<br />
        Windows Firewall on <Tag>{config.managerHostname}</Tag> must allow this inbound connection.
      </p>

      <Toggle
        label="Firewall port already open"
        checked={config.firewallAlreadyOpen}
        onChange={v => update("firewallAlreadyOpen", v)}
        hint={config.firewallAlreadyOpen ? "Skip — setup_firewall.bat won't be generated" : "Generate setup_firewall.bat to open port automatically"}
      />

      {!config.firewallAlreadyOpen ? (
        <InfoBox title="Will generate: setup_firewall.bat" color={T.red}>
          Run as Administrator on <Tag color={T.red}>{config.managerHostname}</Tag> — adds a Windows Firewall inbound rule for TCP {config.managerPort}.
          <br /><br />
          <code style={{ color: "#a3e635", fontSize: "0.7rem" }}>
            netsh advfirewall firewall add rule name="Flamenco Manager {config.managerPort}"<br />
            dir=in action=allow protocol=TCP localport={config.managerPort}
          </code>
        </InfoBox>
      ) : (
        <InfoBox title="Skipped" color={T.green}>
          Firewall script will not be generated. Make sure TCP {config.managerPort} inbound is already allowed on <Tag color={T.green}>{config.managerHostname}</Tag>.
        </InfoBox>
      )}

      <NavRow onBack={onBack} onNext={onNext} nextLabel="Generate Files →" />
    </div>
  );
}

function StepOutput({ config, onBack }) {
  const files = [
    { name: "flamenco-manager.yaml", label: "Manager Config", machine: config.managerHostname, color: T.amber, content: genManagerYaml(config) },
    { name: "flamenco-worker.yaml", label: "Worker Config", machine: config.workerHostname, color: T.blue, content: genWorkerYaml(config) },
    { name: "start_manager.bat", label: "Start Manager", machine: config.managerHostname, color: T.amber, content: genManagerBat(config) },
    { name: "start_worker.bat", label: "Start Worker", machine: config.workerHostname, color: T.blue, content: genWorkerBat(config) },
    ...(!config.shareAlreadyCreated ? [{ name: "setup_share.bat", label: "Create Share", machine: config.managerHostname, color: T.purple, content: genShareBat(config) }] : []),
    ...(!config.firewallAlreadyOpen ? [{ name: "setup_firewall.bat", label: "Firewall", machine: config.managerHostname, color: T.red, content: genFirewallBat(config) }] : []),
  ];

  const [active, setActive] = useState(0);
  const [copied, setCopied] = useState(false);

  const copy = () => {
    navigator.clipboard.writeText(files[active].content).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1600);
    });
  };

  const download = () => {
    const blob = new Blob([files[active].content], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = files[active].name;
    a.click();
  };

  const downloadAll = () => {
    files.forEach((f, i) => {
      setTimeout(() => {
        const blob = new Blob([f.content], { type: "text/plain" });
        const a = document.createElement("a");
        a.href = URL.createObjectURL(blob);
        a.download = f.name;
        a.click();
      }, i * 300);
    });
  };

  const deployOrder = [
    { machine: config.managerHostname, color: T.purple, action: "setup_share.bat — as Administrator", skip: config.shareAlreadyCreated },
    { machine: config.managerHostname, color: T.red, action: "setup_firewall.bat — as Administrator", skip: config.firewallAlreadyOpen },
    { machine: config.workerHostname, color: T.blue, action: `Map drive → ${config.sharedPathUNC}`, skip: false },
    { machine: config.managerHostname, color: T.amber, action: "Copy yaml + exe → run start_manager.bat", skip: false },
    { machine: config.workerHostname, color: T.blue, action: "Copy yaml + exe → run start_worker.bat", skip: false },
    { machine: "BROWSER", color: T.green, action: `Open http://${config.managerIP}:${config.managerPort}/`, skip: false },
  ].filter(s => !s.skip);

  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "1.2rem" }}>
        <div>
          <h2 style={{ color: T.text, fontFamily: T.mono, fontSize: "1.15rem", fontWeight: "800", margin: "0 0 0.25rem" }}>
            Generated Files
          </h2>
          <div style={{ color: T.muted, fontFamily: T.mono, fontSize: "0.75rem" }}>
            {files.length} files ready to deploy
          </div>
        </div>
        <Btn small onClick={downloadAll}>↓ Download All</Btn>
      </div>

      {/* Tabs */}
      <div style={{ display: "flex", flexWrap: "wrap", gap: "0.35rem", marginBottom: "0.6rem" }}>
        {files.map((f, i) => (
          <button
            key={i}
            onClick={() => setActive(i)}
            style={{
              background: active === i ? f.color + "1a" : T.surface,
              border: `1px solid ${active === i ? f.color + "55" : T.border2}`,
              color: active === i ? f.color : T.dim,
              padding: "0.3rem 0.75rem",
              fontFamily: T.mono, fontSize: "0.68rem",
              borderRadius: "3px", cursor: "pointer",
              transition: "all 0.12s", letterSpacing: "0.04em",
            }}
          >
            {f.name}
          </button>
        ))}
      </div>

      {/* Machine badge */}
      <div style={{ display: "flex", alignItems: "center", gap: "0.6rem", marginBottom: "0.5rem" }}>
        <span style={{ color: T.dim, fontFamily: T.mono, fontSize: "0.64rem" }}>DEPLOY TO:</span>
        <Tag color={files[active].color}>{files[active].machine}</Tag>
      </div>

      {/* Code viewer */}
      <div style={{
        background: "#080808", border: `1px solid ${T.border}`,
        borderRadius: "4px", padding: "0.9rem 1rem",
        maxHeight: "240px", overflowY: "auto", marginBottom: "0.6rem",
        scrollbarWidth: "thin", scrollbarColor: `${T.border2} transparent`,
      }}>
        <pre style={{
          color: "#9ca3af", fontFamily: T.mono, fontSize: "0.7rem",
          lineHeight: 1.75, margin: 0, whiteSpace: "pre-wrap", wordBreak: "break-all",
        }}>
          {files[active].content}
        </pre>
      </div>

      <div style={{ display: "flex", gap: "0.5rem", marginBottom: "1.8rem" }}>
        <Btn small onClick={copy}>{copied ? "✓ Copied" : "Copy"}</Btn>
        <Btn small onClick={download}>↓ Download</Btn>
      </div>

      {/* Blender 5.1 manifest fix warning */}
      <div style={{
        background: T.amber + "12", border: `1px solid ${T.amber}33`,
        borderLeft: `3px solid ${T.amber}`, borderRadius: "3px",
        padding: "0.9rem 1rem", marginBottom: "1.2rem",
      }}>
        <div style={{ color: T.amber, fontSize: "0.64rem", letterSpacing: "0.14em", textTransform: "uppercase", fontFamily: T.mono, marginBottom: "0.5rem" }}>
          ⚠ Blender 5.1 — Extra Step Required
        </div>
        <div style={{ color: T.muted, fontSize: "0.74rem", fontFamily: T.mono, lineHeight: 1.7 }}>
          Blender 5.1 uses a new extensions system that requires a manifest file the Flamenco addon
          does not include. Without it, Blender silently refuses to load the addon — no error message.
          <br /><br />
          Download <code style={{ color: T.amber }}>blender_manifest.toml</code> from the GitHub repo
          and place it in the Flamenco addon folder on <strong style={{ color: T.text }}>both machines</strong>:
          <br /><br />
          <code style={{ color: "#9ca3af", fontSize: "0.68rem", display: "block", background: "#080808", padding: "0.5rem 0.75rem", borderRadius: "3px", marginTop: "0.3rem" }}>
            C:\Users\[USERNAME]\AppData\Roaming\Blender Foundation\<br />
            Blender\5.1\extensions\user_default\flamenco\
          </code>
          <br />
          <a href="https://github.com/guilderbeast/flamenco-win11-blender5-setup" target="_blank" rel="noreferrer"
            style={{ color: T.blue }}>
            → github.com/guilderbeast/flamenco-win11-blender5-setup
          </a>
        </div>
      </div>

      {/* Deployment checklist */}
      <div style={{
        background: T.surface, border: `1px solid ${T.border}`,
        borderRadius: "4px", padding: "1.1rem",
      }}>
        <div style={{ color: T.amber, fontSize: "0.64rem", letterSpacing: "0.16em", textTransform: "uppercase", fontFamily: T.mono, marginBottom: "1rem" }}>
          Deployment Order
        </div>
        {deployOrder.map((s, i) => (
          <div key={i} style={{ display: "flex", gap: "0.75rem", marginBottom: "0.65rem", alignItems: "flex-start" }}>
            <span style={{ color: T.dim, fontFamily: T.mono, fontSize: "0.72rem", flexShrink: 0, minWidth: "1.2rem" }}>{i + 1}.</span>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem", alignItems: "center" }}>
              <Tag color={s.color}>{s.machine}</Tag>
              <span style={{ color: T.muted, fontFamily: T.mono, fontSize: "0.74rem" }}>{s.action}</span>
            </div>
          </div>
        ))}
      </div>

      <div style={{ marginTop: "1.2rem" }}>
        <Btn secondary onClick={onBack}>← Back</Btn>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════
//  MAIN APP
// ═══════════════════════════════════════════════════════════════

const STEP_LABELS = ["Start", "Windows", "Roles", "Network", "Storage", "Blender", "Firewall", "Files"];

export default function App() {
  const [step, setStep] = useState(0);
  const [config, setConfig] = useState({
    windowsPro: undefined,
    managerHostname: "PC1",
    workerHostname: "PC2",
    managerIP: "192.168.1.100",
    workerIP: "192.168.1.101",
    managerPort: "8080",
    sharedLocalPath: "C:\\FlamencoShared",
    sharedPathUNC: "\\\\PC1\\FlamencoShared",
    blenderPathManager: "C:\\Program Files\\Blender Foundation\\Blender 4.2\\blender.exe",
    blenderPathWorker: "C:\\Program Files\\Blender Foundation\\Blender 4.2\\blender.exe",
    firewallAlreadyOpen: false,
    shareAlreadyCreated: false,
  });

  const update = (key, val) => setConfig(c => ({ ...c, [key]: val }));
  const next = () => setStep(s => Math.min(s + 1, STEP_LABELS.length - 1));
  const back = () => setStep(s => Math.max(s - 1, 0));
  const props = { config, update, onNext: next, onBack: back };

  return (
    <div style={{
      minHeight: "100vh", background: T.bg,
      display: "flex", alignItems: "flex-start",
      justifyContent: "center", padding: "2.5rem 1rem",
    }}>
      <div style={{ width: "100%", maxWidth: "600px" }}>

        {/* Top bar */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "0.4rem" }}>
          <div style={{ color: "#1e1e1e", fontSize: "0.62rem", letterSpacing: "0.12em", fontFamily: T.mono }}>
            FLAMENCO WIZARD
          </div>
          <div style={{ color: "#2a2a2a", fontSize: "0.62rem", fontFamily: T.mono }}>
            {step + 1}/{STEP_LABELS.length}
          </div>
        </div>

        {/* Progress bar */}
        <div style={{ height: "1px", background: "#111", marginBottom: "1.5rem" }}>
          <div style={{
            height: "1px", background: T.amber,
            width: `${(step / (STEP_LABELS.length - 1)) * 100}%`,
            transition: "width 0.3s ease",
            boxShadow: `0 0 8px ${T.amber}`,
          }} />
        </div>

        {/* Step dots */}
        <div style={{ display: "flex", gap: "0.35rem", marginBottom: "2rem", alignItems: "center" }}>
          {STEP_LABELS.map((label, i) => (
            <div
              key={i}
              onClick={() => i < step && setStep(i)}
              title={label}
              style={{
                height: 6, borderRadius: 3,
                width: i === step ? 24 : 6,
                background: i === step ? T.amber : i < step ? T.amber + "55" : T.border2,
                transition: "all 0.2s",
                cursor: i < step ? "pointer" : "default",
              }}
            />
          ))}
        </div>

        {/* Card */}
        <div style={{
          background: T.card, border: `1px solid ${T.border}`,
          borderRadius: "6px", padding: "2rem",
        }}>
          {step === 0 && <StepIntro onNext={next} />}
          {step === 1 && <StepWindowsCheck {...props} />}
          {step === 2 && <StepRoles {...props} />}
          {step === 3 && <StepNetwork {...props} />}
          {step === 4 && <StepStorage {...props} />}
          {step === 5 && <StepBlender {...props} />}
          {step === 6 && <StepFirewall {...props} />}
          {step === 7 && <StepOutput config={config} onBack={back} />}
        </div>

        {/* Footer */}
        <div style={{ textAlign: "center", marginTop: "1.5rem", color: "#1a1a1a", fontSize: "0.62rem", fontFamily: T.mono }}>
          FLAMENCO RENDER FARM SETUP WIZARD
        </div>
      </div>
    </div>
  );
}
